export const photos = [
  {
    title: 'Электроника и гаджеты',
    description: 'Электроника и гаджеты',
    name: 'elektronika_gadzhety',
    items: [
      {
        title: 'Микрофон',
        name: 'mikrofon',
        photos: [
          '1.webp',
          '12.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
          '9.webp',
          '91.webp',
          '92.webp',
          '93.webp',
          '94.webp',
          '95.webp',
        ],
      },
    ],
  },
  {
    title: 'Одежда, обувь, акссесуары',
    description: 'Одежда и обувь',
    name: 'odezhda_obuv_aksessuary',
    items: [
      {
        title: 'Лонгслив',
        name: 'longsliv',
        photos: [
          '1.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
        ],
      },
      {
        title: 'Подтяжки',
        name: 'podtyazhki',
        photos: ['1.webp', '2.webp', '3.webp', '4.webp', '5.webp', '6.webp'],
      },
      {
        title: 'Халат',
        name: 'khalat',
        photos: [
          '1.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
          '9.webp',
          '91.webp',
          '92.webp',
        ],
      },
    ],
  },
  {
    title: 'Бьюти и уход за собой',
    description: 'Бьюти и уход за собой',
    name: 'byuti_i_ukhod_za_soboy',
    items: [
      {
        title: 'Спонжи',
        name: 'sponzhi',
        photos: [
          '1.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
          '8_.webp',
          '9.webp',
          '99.webp',
        ],
      },
      {
        title: 'Расчестка для волос',
        name: 'rascheska',
        photos: [
          '1.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
        ],
      },
      {
        title: 'Лак для ногтей',
        name: 'gel_lak',
        photos: [
          '1.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
          '9.webp',
          '91.webp',
          '92.webp',
          '93.webp',
          '94.webp',
        ],
      },
    ],
  },
  {
    title: 'Бытовая химия и уборка',
    description: 'Уборка и бытовая химия',
    name: 'bytovaya_khimiya_i_uborka',
    items: [
      {
        title: 'Губки для посуды',
        name: 'gubki_dlya_posudy',
        photos: [
          '1.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
          '9.webp',
        ],
      },
    ],
  },
  {
    title: 'Спортивные товары',
    description: 'Спорт товары и аксессуары',
    name: 'sportivnyye_tovary',
    items: [
      {
        title: 'Мяч',
        name: 'futbolnyy_myach',
        photos: [
          '1.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
        ],
      },
    ],
  },
  {
    title: 'Дом и интерьер',
    description: 'Дом и интерьер',
    name: 'dom_i_interyer',
    items: [
      {
        title: 'Камни для бани',
        name: 'kamni_dlya_bani_sauny',
        photos: [
          '11.webp',
          '12.webp',
          '2.webp',
          '3.webp',
          '4.webp',
          '5.webp',
          '6.webp',
          '7.webp',
          '8.webp',
          '9.webp',
          '91.webp',
        ],
      },
    ],
  },
];
